version: '3.8'

services:
  app:
    image: ${APP_NAME}:local
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/app/src
