version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: ${DB_NAME}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    image: nestjs:local
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/app/src
    depends_on:
      - db
